### ISSUE TITLE
No customer field

### ISSUE THREAD

**Issue by troubleshootme** [owlysk/CodeTimer#2]
No customer value in app, only project. 
Lack of customer field makes this app impossible for me to use as I have a default project for each customer.
Consider adding customer value please.
Otherwise, this looks great.

**Comment by owlysk** [comment]
Hi, I'll add customer field in next version.

**Comment by owlysk** [comment]
Hi again. I have question for you. Changing project is not working for you? Because I just look in API documentation and timesheet has only project value. Customer is related to project, no to timesheet.

Do you have same project name for every customer? If so, maybe will be enough to add customer name in project field at end of each project, like ```ProjectName, Customer #1```. What do you think about that?

**Comment by troubleshootme** [comment]
I have some unique projects for each customer but every customer has a
default project that I put general support entries in.
Have you used the Kemai windows app?
It has a customer drop down that populates and when you select a customer,
it populates a project drop down with that customer's projects.
Sorry I can't be of more help.


Tony Bruno / Consultant

***@***.*** / 205.876.3715

Bruno Computer Support

www.troubleshootme.com <https://troubleshootme.com/>

205.876.3715

**Comment by owlysk** [comment]
Hi,
thanks for additional information. Check out the new release - [v1.0.5](https://github.com/owlysk/CodeTimer/releases/tag/v1.0.5), I added the customer field you were looking for. I hope this will work for you.

**Comment by troubleshootme** [comment]
That's exactly what I needed and your app works and looks great, thank you!
