### ISSUE TITLE
BUG: Incompatible with recent Kimai Version 2.0.33

### ISSUE THREAD

**Issue by xstable** [owlysk/CodeTimer#8]
I've upgraded Kimai to 2.0.33 some minutes ago. 
Now I don't get a Project, NOR actions for a new task.
Not for new Tasks, and even not for any recent tasks: 

![image](https://github.com/owlysk/CodeTimer/assets/1778068/68db2d88-f976-4b75-9c47-987ca9272d1c)

![image](https://github.com/owlysk/CodeTimer/assets/1778068/cdabd693-2538-4e2c-8465-b40fbea9f22e)

![image](https://github.com/owlysk/CodeTimer/assets/1778068/4a06fc1d-73f2-4f4a-8a5c-f3b3ff089c8c)

Whole Cache-Object is empty : 
![image](https://github.com/owlysk/CodeTimer/assets/1778068/ce680abb-e0c7-49af-882c-8a0285d15dd0)

**Comment by owlysk** [comment]
Did you try refresh cache? Button for refresh cache is located in setting, next to back button.

**Comment by xstable** [comment]
Yes, refresh-button, disable (also re-enabeling) caching in dev-tools, etc.

I'd closed it till now and used the integrated (web-base) tracker of kimai. 
But now I've started it again and ... strange enough, currently it work again, and I don't know why.

**Comment by owlysk** [comment]
Hi,
I mean this button, no any cache in dev-tools.
![codeTimer-cache-refresh](https://github.com/owlysk/CodeTimer/assets/79711410/46cf8a09-1a5f-428b-beaa-2b6fa623ab6d)

I think this was happends:
When you start CodeTimer, cache was old, so CodeTimer tries to load actual data. Kimai server was not ready yet, so there was no response from server, cache was empty. Then you tried to load timesheets, server was ready, but cache was still empty - that's why you have not any customer/activity/project. When you click to this button, cache should be refreshed and everything should work normalny. Cache is valid for one hour, so after you reopen CodeTimer after one hour, cache is automatic calling Kimai server, then loads actual data and app will work.

I also installed Kimai v 2.0.33 and have not any issue with CodeTimer.
